### ISSUE TITLE
Ozi-Bots-V13 gelecekmi 

### ISSUE THREAD

**Issue by acerhizmq** [JaylenOzi/Ozi-Destek-Bots-V13#1]
Birkaç defa bir yerlerde geleceğini gördüm star gelirse paylaşıyorum vs sende demiştin galiba peki discord u salmadan önce paylaşacakmısın?

**Comment by JaylenOzi** [comment]
Yeterli star gelmediği için sildim açtığım readme olan repoyu fork yapan kişilerin repoları kalmış destek botuna güzel star gelirse paylaşabilirim...

**Comment by acerhizmq** [comment]
Açık açık söylemek gerekirse githubda bulunan en
iyi supervisor botu olabilir bunun v13 halide büyük bir ses getirecektir. Destek botunun starına bağlamak yerine paylaşman daha iyidir bence..

**Comment by JaylenOzi** [comment]
starı isteme sebebim botun yaygınlaşıp kullanılması ozi botsu v13 yapınca düşük star gelicek tanınmayacak belkide v12 sürümünde sunuculara botu paralı olarak yapanlar var burda ücretsiz paylaşmama rağmen aynı durum olması beni üzer o yüzden şuan paylaşma gibi kararım yok.

**Comment by acerhizmq** [comment]
Doğru söylemek gerekirse botunu kendi sunucumda kullanıyorum. Birçok kişiyede senin olduğunu söylüyorum.
Özellikleri vs fazlasıyla yeterli v12 desteğinin biteceğinin kararı alındığında ilk baktığım açtığın repoya bakmaktı, v13 hali eğer gerçektende star gelir ise paylaşıldığında ilgi göreceğini düşünüyorum. Bana versende olur 😁.
O kendimin diye ortalıkta gezenler her yerde var.

**Comment by JaylenOzi** [comment]
Gezmelerini umursamam açıkçası kanka bilen bilir zaten de parayla satmaları komik :D

**Comment by acerhizmq** [comment]
Para karşılığı github reposundan bir bot satmak ne bileyim çocukça bir iş anlam veremiyorum. Buradan konuşmak yerine discord üzerinden konuşalım bi ara yazmıştım sana acerhizm ヤ#0360 belki hatırlarsın.
